### ISSUE TITLE
openai.error.RateLimitError: 

### ISSUE THREAD

**Issue by merolaika** [eddieoz/reels-clips-automator#2]
Hello, i have limit on open ai but it will error.. i Put my open api key into .env file and my video time 04:11 long

`(reels-clips-automator) C:\ai\reels-clips-automator>python reelsfy.py -v https://www.youtube.com/watch?v=Cuptv7-A4p0`
`[WinError 183] Cannot create an existing file: 'results'`
`[WinError 123] Incorrect file name, directory name or volume label syntax: 'results/https://www.youtube.com/watch?v=Cuptv7-A4p0'`

but this file does not already exist and gives this error when first created

`Traceback (most recent call last):
  File "C:\ai\reels-clips-automator\reelsfy.py", line 313, in <module>
    __main__()
  File "C:\ai\reels-clips-automator\reelsfy.py", line 285, in __main__
    viral_segments = generate_viral(transcript)
  File "C:\ai\reels-clips-automator\reelsfy.py", line 198, in generate_viral
    response = openai.ChatCompletion.create(
  File "C:\Users\mero\.conda\envs\reels-clips-automator\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\mero\.conda\envs\reels-clips-automator\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\mero\.conda\envs\reels-clips-automator\lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\mero\.conda\envs\reels-clips-automator\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\mero\.conda\envs\reels-clips-automator\lib\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.`

**Comment by MinightDev** [comment]
> Hello, i have limit on open ai but it will error.. i Put my open api key into .env file and my video time 04:11 long
> 
> `(reels-clips-automator) C:\ai\reels-clips-automator>python reelsfy.py -v https://www.youtube.com/watch?v=Cuptv7-A4p0` `[WinError 183] Cannot create an existing file: 'results'` `[WinError 123] Incorrect file name, directory name or volume label syntax: 'results/https://www.youtube.com/watch?v=Cuptv7-A4p0'`
> 
> but this file does not already exist and gives this error when first created
> 
> `Traceback (most recent call last): File "C:\ai\reels-clips-automator\reelsfy.py", line 313, in <module> __main__() File "C:\ai\reels-clips-automator\reelsfy.py", line 285, in __main__ viral_segments = generate_viral(transcript) File "C:\ai\reels-clips-automator\reelsfy.py", line 198, in generate_viral response = openai.ChatCompletion.create( File "C:\Users\mero\.conda\envs\reels-clips-automator\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create return super().create(*args, **kwargs) File "C:\Users\mero\.conda\envs\reels-clips-automator\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create response, _, api_key = requestor.request( File "C:\Users\mero\.conda\envs\reels-clips-automator\lib\site-packages\openai\api_requestor.py", line 298, in request resp, got_stream = self._interpret_response(result, stream) File "C:\Users\mero\.conda\envs\reels-clips-automator\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response self._interpret_response_line( File "C:\Users\mero\.conda\envs\reels-clips-automator\lib\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line raise self.handle_error_response( openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.`

Maybe this script is written to only work on linux. For the openai error you need a new api key because you exceeded your current quota

**Comment by eddieoz** [comment]
Maybe it is needed to create a new account or to subscribe to their service.
